//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animaux
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animaux()
        {
            this.Animaux_maladies = new HashSet<Animaux_maladies>();
            this.Ordonnance = new HashSet<Ordonnance>();
            this.Rappel = new HashSet<Rappel>();
            this.Race = new HashSet<Race>();
            this.Soins = new HashSet<Soins>();
        }
    
        public int idAnimaux { get; set; }
        public string Nom { get; set; }
        public string Sexe { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public Nullable<int> Poids { get; set; }
        public Nullable<System.DateTime> DernièreVisite { get; set; }
        public Nullable<System.DateTime> ProchaineVisite { get; set; }
        public string Caractéristiques { get; set; }
        public int Clients_idClients { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animaux_maladies> Animaux_maladies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordonnance> Ordonnance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rappel> Rappel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Race> Race { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soins> Soins { get; set; }
    }
}
