//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animaux_maladies
    {
        public int Animaux_idAnimaux { get; set; }
        public int Maladies_idMaladies { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Animaux Animaux { get; set; }
        public virtual Maladies Maladies { get; set; }
    }
}
