//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int idLogs { get; set; }
        public System.DateTime Date { get; set; }
        public int Employés_idEmployés { get; set; }
        public string Action { get; set; }
    
        public virtual Employés Employés { get; set; }
    }
}
