//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PT4_S4P2C_E3Entities : DbContext
    {
        public PT4_S4P2C_E3Entities()
            : base("name=PT4_S4P2C_E3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animaux> Animaux { get; set; }
        public virtual DbSet<Animaux_maladies> Animaux_maladies { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Comestibles> Comestibles { get; set; }
        public virtual DbSet<Congés> Congés { get; set; }
        public virtual DbSet<Employés> Employés { get; set; }
        public virtual DbSet<Especes> Especes { get; set; }
        public virtual DbSet<Factures> Factures { get; set; }
        public virtual DbSet<Fonctions> Fonctions { get; set; }
        public virtual DbSet<Formations> Formations { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Maladies> Maladies { get; set; }
        public virtual DbSet<Matériels> Matériels { get; set; }
        public virtual DbSet<Médicaments> Médicaments { get; set; }
        public virtual DbSet<Nourriture> Nourriture { get; set; }
        public virtual DbSet<Ordonnance> Ordonnance { get; set; }
        public virtual DbSet<Produits> Produits { get; set; }
        public virtual DbSet<Race> Race { get; set; }
        public virtual DbSet<Rappel> Rappel { get; set; }
        public virtual DbSet<RendezVous> RendezVous { get; set; }
        public virtual DbSet<RoleUser> RoleUser { get; set; }
        public virtual DbSet<Soins> Soins { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_congés> Type_congés { get; set; }
        public virtual DbSet<Utilisateurs> Utilisateurs { get; set; }
    }
}
