//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nourriture
    {
        public int idNourriture { get; set; }
        public int Comestibles_idComestibles { get; set; }
        public int Comestibles_Produits_idProduits { get; set; }
        public int Comestibles_Produits_idProduits1 { get; set; }
    
        public virtual Comestibles Comestibles { get; set; }
    }
}
