//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produits()
        {
            this.Ordonnance = new HashSet<Ordonnance>();
        }
    
        public int idProduits { get; set; }
        public string refProduits { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAcquisition { get; set; }
        public int PrixAcquisition { get; set; }
        public int PrixVente { get; set; }
    
        public virtual Comestibles Comestibles { get; set; }
        public virtual Matériels Matériels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordonnance> Ordonnance { get; set; }
    }
}
